import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const repoRoot = process.cwd();
const sourcePath = path.join(repoRoot, 'src', 'symbol-catalog.json');
const outputPath = path.join(repoRoot, 'src', 'CatalogData.gs');

const sourceText = fs.readFileSync(sourcePath, 'utf8').trim();
let catalog;

try {
  catalog = JSON.parse(sourceText);
} catch (jsonError) {
  const scriptText = sourceText.replace(/^const\s+ASTRO_SYMBOLS_CATALOG\s*=\s*/, '').replace(/;\s*$/, '');
  catalog = vm.runInNewContext(scriptText, {});
}

if (!Array.isArray(catalog)) {
  throw new Error('symbol-catalog.json must resolve to an array.');
}

const output = [
  '// Generated from src/symbol-catalog.json by scripts/sync-catalog.mjs',
  '// Do not edit this file directly.',
  'var ASTRO_SYMBOLS_CATALOG = ' + JSON.stringify(catalog, null, 2) + ';',
  ''
].join('\n');

fs.writeFileSync(outputPath, output, 'utf8');
console.log('Generated ' + path.relative(repoRoot, outputPath));
